version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=warehouse
      - MYSQL_USER=localhost
      - MYSQL_PASSWORD=root
    volumes:
      - /data/mysql
  warehouse-app:
    image: data-warehouse-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:9090
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/warehouse?createDatabaseIfNotExist=true
    volumes:
      - /data/spring-boot-app
