version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=localhost
    ports:
      - "3306:3306"
    restart: always
  warehouse-app:
    image: warehouse-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker-container:3306/warehouse?createDatabaseIfNotExist=true

